# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run CTRF annotations
        run: npx github-actions-ctrf ctrf-report.json
        if: ${{ hashFiles('target/surefire-reports/qt3ts-runner-fn-*.xml') }}
  wiki-update:
    runs-on: ubuntu-latest
    needs: [build]
    name: Update wiki with generated content
    steps:
#      - uses: actions/checkout@v4
#        with:
#          repository: ${{ github.repository }}.wiki
#          path: 'wiki'
      - name: Run a one-line script
        run: |
          mkdir -p target/wiki
          echo Generated content foo bar >> target/wiki/generated_page_2.md
#      - uses: OrlovM/Wiki-Action@v1
#        with:
#          path: 'wiki'
#          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: nico@nkutsche.com
          ACTION_NAME: nkutsche
          GH_PAT: ${{ secrets.GH_PAT }}
#          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          MD_FOLDER: target/wiki
          OWNER: nkutsche
          REPO_NAME: github-action-tests
  
